import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const source = await readFile(new URL('../chat-relay/src/worker.js', import.meta.url), 'utf8');
const {default: worker} = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
let deliveries = 0;
let deliveryStatus = 204;
globalThis.fetch = async () => { deliveries++; return new Response(null,{status:deliveryStatus}); };
const env = {DISCORD_CONTACT_WEBHOOK_URL:'https://example.invalid/test-webhook'};
const request = (body) => new Request('https://example.invalid/api/contact',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://wrapdbtc.github.io'},body:JSON.stringify(body)});
const data={name:'Test',email:'test@example.invalid',message:'A test inquiry, never sent externally.'};
let r=await worker.fetch(new Request('https://example.invalid/api/contact'),env,{});
assert.equal(r.status,200); assert.equal((await r.json()).phoneOptional,true);
r=await worker.fetch(request(data),env,{}); assert.equal(r.status,200);assert.equal(deliveries,1);
r=await worker.fetch(request({...data,phone:'12'}),env,{});assert.equal(r.status,400);assert.equal(deliveries,1);
r=await worker.fetch(request({...data,_gotcha:'bot'}),env,{});assert.equal(r.status,200);assert.equal(deliveries,1);
r=await worker.fetch(request(data),{},{});assert.equal(r.status,503);
deliveryStatus=500;r=await worker.fetch(request(data),env,{});assert.equal(r.status,502);
r=await worker.fetch(request({...data,message:''}),env,{});assert.equal(r.status,400);
console.log('PASS: capability, optional phone, validation, honeypot, missing configuration and failed delivery. No network requests sent.');
